### ISSUE TITLE
Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by mrnmukkas** [Edubits/Zway-MQTT#17]
I'm getting tons of these errors (about 4000 under a 24h period) in my z-way-server.log

> [2017-01-05 15:01:10.706] [E] [core] Callback execution error: TypeError: Cannot read property 'write' of undefined
    at MQTTClient.ping (automation/userModules/MQTT/lib/mqtt.js:578:18)
    at Function.<anonymous> (automation/userModules/MQTT/lib/mqtt.js:164:14)
[2017-01-05 15:01:11.106] [I] [core] [MQTT_45] Error: Error: Timeout
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at null._errorCallback (automation/userModules/MQTT/index.js:105:8)
    at MQTTClient._onError (automation/userModules/MQTT/lib/mqtt.js:449:10)
    at MQTTClient._onTimeout (automation/userModules/MQTT/lib/mqtt.js:443:8)
    at Function.<anonymous> (automation/userModules/MQTT/lib/mqtt.js:575:12)
[2017-01-05 15:01:11.110] [I] [core] [MQTT_45] Error: Disconnected, will retry to connect...
    at MQTT.BaseModule.error (automation/userModules/BaseModule/index.js:122:17)
    at null._disconnectCallback (automation/userModules/MQTT/index.js:109:8)
    at MQTTClient._onClose (automation/userModules/MQTT/lib/mqtt.js:459:10)
    at MQTTClient._onTimeout (automation/userModules/MQTT/lib/mqtt.js:444:8)
    at Function.<anonymous> (automation/userModules/MQTT/lib/mqtt.js:575:12)

I'm currently trying to find out why my entire z-way-server crashes at intermittent intervals and I noticed these error messages in the log. Please note that these messages appear even when the z-way-server is working.

**Comment by Edubits** [comment]
Hi @mrnmukkas, sorry to hear to running into these! Personally I haven't seen them on my install. 
The relevant function is:
```javascript
MQTTClient.prototype.ping = function () {
  var self = this;
  if (!this.connected) {
    this._onError(Error('Please connect to server first'));
    return;
  }

  var buffer = new Buffer(2);
  buffer[0] = MQTTClient.PINGREQ << 4;
  buffer[1] = 0x00;

  this._wait_for_pingresp = true;
  setTimeout(function () {
    if (self._wait_for_pingresp)
      self._onTimeout();
  }, this.options.alive_timer * 1000);

  this.connection.write(buffer);
};
```
The error seems to indicate that when the `this.connection.write(buffer);` is reached the connection is closed (happens in `MQTTClient.prototype._onClose`). As the ping function does check if it is connected this should normally not be possible. As this could be related to timeouts some users experience, maybe @i8beef has an idea?

**Comment by i8beef** [comment]
Yes my changes were hacks around your existing code to try and implement something it wasn't built to do. Unfortunately, the connection management here isn't really easy to follow, so I didn't want to change it much. There is no reconnect throttling here for instance, which you might be able to put into index.js with a setTimeout and a isReconnecting lock? That would at least help with the log growing so quickly as it tries to reconnect over and over.

I also have concerns over the paths to _onClose, and being called multiple times on a disconnect. Again, maybe a check there on isConnected before executing callbacks, etc. to make sure its only called once on a given connection cycle?

Honestly, I would have written this on top of MQTT.js instead, or some other mature upstream library. That would handle these reconnects transparently and you wouldn't have to deal with a lot of this. I might take a look at reimplementing on top of that at some point if I can figure out how the hell you package a node library up into something that ZWay can include... I can't find ANY examples of that though.

**Comment by Edubits** [comment]
It's clear now this is the same issue as in #16, so I'll close this issue. I'll look into your suggestions @i8beef!

> Honestly, I would have written this on top of MQTT.js instead, or some other mature upstream library. That would handle these reconnects transparently and you wouldn't have to deal with a lot of this. I might take a look at reimplementing on top of that at some point if I can figure out how the hell you package a node library up into something that ZWay can include... I can't find ANY examples of that though.

I would love to! However as you already mention there are no examples available for adding a node library. When I set this up I looked into this and experimented with several JS MQTT libraries. Basically they all either are NodeJS, or they need WebSockets. WebSockets would be ideal, but the JS version provided by Z-Way doesn't support this. It's a pity the JS available to Z-Way apps is very limited!
