### ISSUE TITLE
Zway-MQTT disappeared from git and Z-Wave-me app store

### ISSUE THREAD

**Issue by Jochey** [Edubits/Zway-MQTT#27]
Some days ago there was an update to version 1.3.1 of the Zway MQTT app. After the update, the stability seemed to have been fixed and communication was stable. After a couple of days, i have suddenly been sent back to version 1.3 and the app has disappeared from Z-Wave-me app store. The unstability issues has returned. I am not able to get the updated version via git either. Anyone who knows what has happend?

**Comment by Edubits** [comment]
According to the developer console of Z-Wave.me they are still processing the update. I’ve noticed before that during this the plugin is unfortunately not available. What you could try is use the beta key mentioned in the readme, hopefully that helps to install it! I’ll keep an eye on the console and hope they will process it soon!

**Comment by Edubits** [comment]
It was just approved, so the app should be available again!
