### ISSUE TITLE
Initial connect failure fails to trigger reconnect

### ISSUE THREAD

**Issue by i8beef** [Edubits/Zway-MQTT#28]
I have been seeing some odd things when an initial connection times out. It fails to notify that the connection has closed, and thus doesn't trigger the reconnect logic. PR incoming.

**Comment by i8beef** [comment]
Note: I've been running this change on my local instance for several weeks already, and it has been solid with this.

**Comment by i8beef** [comment]
I pushed another change that just kills the reconnect timer on module stop explicitly. I was trying two other changes around disconnect being called, but I reverted them, ignore those. I thought that onClose wasn't getting called on specifically the socket connect failure, only on a protocol connect failure and explicit socket close call... I think the other changes I made here are still good as they close some gaps around module start / stop and protocol connect timeout, though.

I'm keeping an eye on my local for what I suspect is a reconnect issue still though. When I manually attempt to reproduce by bringing my MQTT server down and watching the log, and then bringing it back up, the reconnect logic LOOKS solid... waits 30 seconds for the ping timeout, triggers the onClose, and the disconnect callback, and runs through the reconnects and such, but I've had my connection get lost from time to time when I'm messing with things. I'm still not sure where it's getting tied up when that happens and I haven't been able to get anything helpful from the log.

Thoughts:

1. Perhaps its related to how long the MQTT server is down. I've seen this especially on a long downtime, so that may be a necessary reproduction piece. 
2. It might have to do with some of the module stop logic. Notice the changes I made here around that are an attempt to play with that. My thought is ZWay may be newing up a module instance on start / stop button pushes in the UI, and if said module was in the process of a reconnect, it now has an orphaned timer that is trying to reconnect: i.e., the stop logic needs to be very careful on cleaning up after itself, and it wasn't explicitly killing those reconnect timers. I changed that here thinking it might be a race condition between the orphaned timer and the new module instance.
3. Maybe I'm an idiot and I'm just checking things too quickly. Unclean MQTT shutdowns will leave the module CONNECTED but waiting for the ping timeout to trigger close and reconnect. That's a 30 second timer, and maybe I'm just checking before this occurs and the reconnect is triggered (i.e., I reboot MQTT, and immediately check for connectivity, but the module hasn't even noticed its gone yet even though MQTT is already back up again)? I'll keep it in mind as I test here just in case.

The other changes in that PR should be fine, but I'm still on the hunt for something weird going on.

**Comment by i8beef** [comment]
Just a note here, I've been running pretty solidly on the current branch since March. The change to first setup the client's connection and THEN initiate a connect (along with some extra logging), as well as the change to add the missing close call in mqtt.js on a timeout are the only things in that PR right now, and I think both are good to go.

Note there was some chatter in the ZWave comments on the module about the way you generate a client id as well (not all MQTT servers apparently do what Mosquitto does and automatically kill the older connection on reconnect of the same client id?), just something to look at if you haven't already for another release.

**Comment by Edubits** [comment]
That's great to hear @i8beef! I've been running with your changes for a while now as well without any issues. I'll merge it in soon!

I did miss the comment about the clientId, so I'll look into that as well. I created #30 for this.
