### ISSUE TITLE
Timeout on connecting

### ISSUE THREAD

**Issue by Edubits** [Edubits/Zway-MQTT#36]
It seems that 10s is not always enough to connect, causing timeouts and reconnects. Also noticed that `_connect_timeout_timer` is calling `_onClose` directly instead of `_onTimeout`. The latter actually closes the socket, instead of just cleaning up.

**Comment by Edubits** [comment]
@i8beef just pushed a change for this, are you able to test/verify it? If verified I'll package this version and publish it to Z-Way.

**Comment by i8beef** [comment]
If you call onTimeout instead of onClose you aren't clearing the timeouts. My thought was in the case of calling the onClose, the socket is already closed / not connected. The way you've changed this, it has  the possibility of leaving hanging timeouts, and it also doesn't then call the disconnect timeout. I don't think thats what you want to do?

**Comment by Edubits** [comment]
My reasoning is as follows: `onTimeout` calls `connection.close()`, which after closing the socket will call `onClose` and clears the timeout. If directly calling `onClose` the socket is not closed, but nulled, which might leave the connection open on the other side. If the timeout occurs due to the socket being already closed, it _should_ have called onClose already, so this normally _shouldn't_ happen.

**Comment by i8beef** [comment]
I'd make sure that the socket actually calls `onClose` when the socket hasn't fully connected yet. If it doesn't you'd be leaving those setTimeouts running in the background, which has caused instability in the past when things like reconnect timeouts, ping timeouts, etc. weren't cleaned up. `onTimeout` would be fine on a PING timeouts I think, since it would be running against an open socket... but for a CONNECTION timeout I'm unsure...

**Comment by Edubits** [comment]
Fair point, however the only timer that should be running is the `connect_timeout_timer`, the ping timers are only started after the connection is successfully made. But let's clean them up, just to be sure.

**Comment by i8beef** [comment]
Im just cautious around these timers and the reconnect logic as we've sort of stumbled our way to stability here a bit... the lack of a good debug environment for all this makes a lot of stuff theoretical until its tested in the wild. :-)

I agree connect_timeout_timer SHOULD be the only timer running on a clean connect attempt. And I think we've cleaned up all the spots where a ping timer, etc. would be left hanging orphaned now. So in theory I think you are correct.

_onClose does some other stuff though too.

1. Sets this.connected = false
2. Ensures ALL timers are killed
3. Calls the disconnect callback, which in turn sets up the reconnect timeout.

So if the `this._connection.close();` DOESN'T trigger the _onClose you are going to miss all that and break reconnects...

However with your new changes there, if it DOES trigger _onClose you are going to call all that TWICE, and I think you're going to have two reconnect timers going at the same time (disconnect callback gets called twice), and you'll start hitting some of the weird hanging issues we had before as two connections vie for the socket.

I'm not sure which scenario we fall into here, but both hinge on the internal functionality of the _connection.close() when a connection has not been fully established. Might need to add some debug logging and yank some ethernet cables to try that.

**Comment by i8beef** [comment]
So as it stands now, I'd probably put that back to this:

```
  this._connect_timeout_timer = setTimeout(function() {
                                  self._connect_timeout_timer = null;
                                  self._onTimeout();
                                }, this.options.connect_timeout * 1000);
```

And then try a bad connection and make sure the reconnect logic triggers. If it DOES, then this is fine. If it DOESN'T then we would need to revisit.

**Comment by Edubits** [comment]
You're right, I forgot about the issues coming from the disconnect being called twice. I reverted to using `_onTimeout()` in the timeout. I did several tests (both with actually getting rid of the connection and by simulating timeouts in code at a few different points in the execution) and it was able to recover from them. I'll run it locally for some days longer to test, but I'm pretty confident we can push this as a new version.

**Comment by i8beef** [comment]
If you try connecting to a bad IP, do you see the reconnects triggering in logging? As long as you do see those kick off with this code, then the onClose is triggering correctly even when the connection isn't fully established, but _connection.close() is called (by onTimeout). As long as that works correctly, I think you should be good here.

**Comment by Edubits** [comment]
FYI: version 1.4.1 was submitted to the app store pending verification
