### ISSUE TITLE
messages from switches

### ISSUE THREAD

**Issue by mcfanda** [Edubits/Zway-MQTT#6]
switches work!

**Comment by Edubits** [comment]
Thanks for confirming, care to share what went wrong in the first place?

**Comment by mcfanda** [comment]
Yes, I thought switches did not work. They were set up in one of the many mqtt app instances I have. It was the third app instance I set up.  Now I removed that instance and put the switches in the first instance I've created, and they work. I've done some testing and it seems that when I set up many instances of the mqtt app, the last one does not work.

**Comment by Edubits** [comment]
Thanks for explaining @mcfanda! The app is made to run only once, so this is likely the cause. There is an option now in Zway to make an app a Singleton, but I've yet to implement this. After that it's not possible to create multiple instances anymore.

**Comment by mcfanda** [comment]
great, I'm now using the "tags" option and it works like a charm with only one app
