### ISSUE TITLE
Authenticated MQTT broker

### ISSUE THREAD

**Issue by outlawza** [Edubits/Zway-MQTT#9]
Hi Robin 

Firstly i would like to say a massive thanks for this tool. It is working really well and i have managed to get it to automate my Home Assistant in ways i never thought possible. 

I just have one little issue. For some reason (probably my own stupidity) i cant seem to get thiis app working when my MQTT broker does not allow guest access. I have looked through the modules.json and mqtt.js files but dont really see anywhere where to authenticate this app to the broker. As soon as i allow guest access to the broker all works perfectly. I really hope it is something stupid that i am doing and not the design of the application. 

I have entered my user credentials into the modules.json file but it has not resolved the issue. 

Thanks 

Terry

**Comment by Edubits** [comment]
Unfortunately the JavaScript MQTT library I'm currently using doesn't support authentication. I haven't found a reliable alternative yet which does, any suggestions are welcome. The library should be pure JavaScript and not rely on WebSockets (which are not available in Z-Way JS).

**Comment by pathec** [comment]
Hi @Edubits, perhaps Eclipse Paho would be an alternative. There is a [JavaScript client implementation](https://eclipse.org/paho/clients/js/).

**Comment by Jocke-G** [comment]
Hi,

The library you are using really looks like it does support authentication. The constructor of MQTTClient takes an options object, which has both username and password.

**Comment by Edubits** [comment]
@pathec Unfortunately: 
> The client should work in any browser fully supporting WebSockets, http://caniuse.com/websockets lists browser compatibility.

@Jocke-G It should indeed, but in practise it doesn't seem to work as advertised.

**Comment by Edubits** [comment]
Sorry, I was mistaken while answering this question, I was confusing with SSL, which is an issue. Could you guys give PR #14 a try before I merge it to the master?

**Comment by duiffie** [comment]
#14 works perfectly for me!

**Comment by Edubits** [comment]
Great, thanks for checking it as well @duiffie! I'll be merging it in soon.

**Comment by Jocke-G** [comment]
Great this is solved!
I have installed Zway-MQTT through "Zwave.me App Store". How do I upgrade to get this version supporting authentucation?

**Comment by Edubits** [comment]
@Jocke-G I will have to upload a new version, I'll do that soon!

**Comment by Edubits** [comment]
@Jocke-G the new version is uploaded as 1.1. It still has to be verified by Z-wave.me, but if you add `mqtt_beta` to your App Store Access Tokens you'll be able to install it already.

**Comment by outlawza** [comment]
Hi Robin 

I have just returned from holiday and am super excited to see that there has been some work done on this issue. I will install the new version and test to see if the authentication works. This does make me all warm and fuzzy. 

Thanks again

Terry
